name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: analytics_user
          POSTGRES_PASSWORD: analytics_pass
          POSTGRES_DB: analytics_dashboard
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      influxdb:
        image: influxdb:2.4
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: admin
          DOCKER_INFLUXDB_INIT_PASSWORD: admin123
          DOCKER_INFLUXDB_INIT_ORG: analytics
          DOCKER_INFLUXDB_INIT_BUCKET: metrics
        ports:
          - 8086:8086
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Run build
      run: ./gradlew build
    
    - name: Build Docker image
      run: docker build -t analytics-dashboard:${{ github.sha }} .
    
    - name: Run security scan
      uses: anchore/scan-action@v3
      with:
        image: "analytics-dashboard:${{ github.sha }}"
        fail-build: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/build/test-results/test/
          **/build/reports/tests/test/